CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
CONFIG += no_fixpath
QT = core gui sql websockets widgets
